name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-cabal:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.0.2', '8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.1', '9.2.1']
        cabal: ['3.6.2.0']

    steps:
    - uses: actions/checkout@v2

    - if: matrix.os == 'windows-latest'
      name: Install ghcup on windows
      run: Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $false,$true,$true,$false,$false,$false,$false,"C:\","", "C:\msys64"

    - if: matrix.os == 'windows-latest'
      name: Install make on windows
      run: C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm make"

    - if: matrix.os == 'windows-latest'
      name: Add ghcup to PATH
      run: echo "C:\ghcup\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - if: matrix.os != 'windows-latest'
      name: Install ghcup on non-windows
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH

    - name: Install ghc/cabal
      run: |
        ghcup install ghc ${{ matrix.ghc }}
        ghcup install cabal ${{ matrix.cabal }}
      shell: bash

    - name: Update cabal index
      run: cabal update
      shell: bash

    - if: matrix.os == 'windows-latest'
      name: Install cpphs
      run: cabal install --installdir="C:\ghcup\bin" --overwrite-policy=always --install-method=copy cpphs

    - if: matrix.os != 'windows-latest'
      name: Install cpphs
      run: cabal install --overwrite-policy=always --install-method=copy cpphs
      shell: bash

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks
      shell: bash

    - name: Run tests
      run: cabal test
      shell: bash

    - name: Haddock
      run: cabal haddock
      shell: bash

    - name: Check generation
      run: |
        make all
        git diff --exit-code
      shell: bash

    - name: check
      run: cabal check
      shell: bash

    - name: sdist
      run: cabal sdist
      shell: bash
